name: cards_against_humanity
description: Not so politically correct.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1


environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.0.2
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/csv/question.csv
    - assets/csv/answers.csv