name: cards_against_humanity
description: Not so politically correct.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1


environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  csv: ^5.0.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  url_launcher: ^6.1.12
  flutter_file_downloader: ^1.1.2
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/csv/questions.csv
    - assets/csv/answers.csv
    - assets/eastereggs/104_0.jpeg
    - assets/eastereggs/104_1.jpeg
    - assets/eastereggs/104_2.jpeg
    - assets/eastereggs/104_3.jpeg
    - assets/eastereggs/104_4.jpeg
    - assets/eastereggs/104_5.jpeg
    - assets/eastereggs/104_6.jpeg
    - assets/eastereggs/104_7.jpeg
    - assets/eastereggs/104_8.jpeg
    - assets/eastereggs/104_9.jpeg
    - assets/eastereggs/104_10.jpeg
    - assets/eastereggs/104_11.jpeg